

services:
  postgres:
    image: postgres:16-alpine
    container_name: restaurante-postgres
    environment:
      - POSTGRES_DB=restaurante_bot_db
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: # Volumen nombrado para que tus datos no se borren al apagar el contenedor